use crate::attrs::{ConvertType, EntityAttr, FieldAttr};
use crate::transform::count_transform_params;
use proc_macro2::Span;
use std::convert::TryFrom;
use syn::spanned::Spanned;
use syn::*;

#[derive(Clone)]
pub struct EntityField {
    pub get_one: Option<Ident>,
    pub get_optional: Option<Ident>,
    pub get_many: Option<Ident>,
    pub set: Option<Ident>,
    pub delete: Option<Ident>,
    pub convert: Option<ConvertType>,
    pub transform_get: Option<String>,
    pub transform_set: Option<String>,
    pub transform_get_params: Option<ExprPath>,
    pub transform_set_params: Option<ExprPath>,
    pub column_name: String,
    pub ident: Ident,
    pub ty: Type,

    pub is_key: bool,
    pub autogenerated: bool,
    pub updatable: bool,
    pub patchable: bool,
    pub custom_type: bool,
}

impl EntityField {
    pub fn fmt_for_select(&self) -> String {
        let ident = self.ident.to_string().replace("r#", "");
        let column_name = self.column_name.to_string().replace("r#", "");

        if self.custom_type {
            format!(r#"{} AS "{}: _""#, column_name, ident)
        } else if ident != column_name {
            format!("{} AS {}", column_name, ident)
        } else {
            ident
        }
    }

    pub fn fmt_expression_alias(&self) -> String {
        let ident = self.ident.to_string().replace("r#", "");
        let nullable_suffix = if is_option_type(&self.ty) { "?" } else { "!" };

        if self.custom_type {
            format!(r#""{}{}: _""#, ident, nullable_suffix)
        } else {
            format!(r#""{}{}""#, ident, nullable_suffix)
        }
    }
}

pub struct Entity {
    pub table_name: String,
    pub ident: Ident,
    pub fields: Vec<EntityField>,
    pub vis: Visibility,

    pub get_all: Option<Ident>,
    pub delete: Option<Ident>,

    pub update: Ident,
    pub insert: Option<Ident>,
    pub patch: Option<Ident>,

    pub before_patch: Option<ExprPath>,
    pub after_patch: Option<ExprPath>,
    pub before_update: Option<ExprPath>,
    pub after_update: Option<ExprPath>,
    pub before_insert: Option<ExprPath>,
    pub after_insert: Option<ExprPath>,
    pub before_delete: Option<ExprPath>,
    pub after_delete: Option<ExprPath>,

    pub error_type: Option<Ident>,
    pub context_type: Option<Ident>,
}

impl Entity {
    pub fn insertable_fields(&self) -> impl Iterator<Item = &EntityField> {
        self.fields.iter().filter(move |field| !field.autogenerated)
    }

    pub fn patchable_fields(&self) -> impl Iterator<Item = &EntityField> {
        self.fields.iter().filter(move |field| field.patchable)
    }

    pub fn updatable_fields(&self) -> impl Iterator<Item = &EntityField> {
        self.fields.iter().filter(move |field| field.updatable)
    }
}

impl TryFrom<&Field> for EntityField {
    type Error = Error;

    fn try_from(field: &Field) -> Result<Self> {
        let ident = field.ident.clone().unwrap();
        let get_ident =
            |prefix: &str| Ident::new(&format!("{}_{}", prefix, ident), Span::call_site());

        let mut result = EntityField {
            get_one: None,
            get_optional: None,
            get_many: None,
            delete: None,
            set: None,
            convert: None,
            transform_get: None,
            transform_set: None,
            transform_get_params: None,
            transform_set_params: None,
            ty: field.ty.clone(),
            column_name: ident.to_string(),
            ident: ident.clone(),
            is_key: false,
            updatable: true,
            patchable: true,
            autogenerated: false,
            custom_type: false,
        };
        let mut has_updatable_set = false;
        let mut has_patchable_set = false;
        for attr in crate::attrs::parse_all::<FieldAttr>(&field.attrs)? {
            match attr {
                FieldAttr::Rename(r) => result.column_name = r,
                FieldAttr::GetOne(g) => {
                    let fn_name = g.unwrap_or_else(|| get_ident("get_by"));
                    result.get_one = Some(fn_name)
                }
                FieldAttr::GetOptional(g) => {
                    let fn_name = g.unwrap_or_else(|| get_ident("get_by"));
                    result.get_optional = Some(fn_name);
                }
                FieldAttr::GetMany(g) => {
                    let fn_name = g.unwrap_or_else(|| get_ident("get_by"));
                    result.get_many = Some(fn_name);
                }
                FieldAttr::Delete(g) => {
                    let fn_name = g.unwrap_or_else(|| get_ident("delete_by"));
                    result.delete = Some(fn_name)
                }
                FieldAttr::Set(s) => {
                    let fn_name = s.unwrap_or_else(|| get_ident("set"));
                    result.set = Some(fn_name);
                }
                FieldAttr::Updatable(updatable) => {
                    has_updatable_set = updatable;

                    result.updatable = updatable;
                }
                FieldAttr::Patchable(patchable) => {
                    has_patchable_set = patchable;

                    result.patchable = patchable;
                }
                FieldAttr::Key => {
                    result.is_key = true;
                }
                FieldAttr::Default => {
                    result.autogenerated = true;
                }
                FieldAttr::CustomType => {
                    result.custom_type = true;
                }
                FieldAttr::Convert(function) => result.convert = Some(function),
                FieldAttr::TransformGet(transform) => result.transform_get = Some(transform),
                FieldAttr::TransformSet(transform) => result.transform_set = Some(transform),
                FieldAttr::TransformGetParams(params) => {
                    result.transform_get_params = Some(params);
                }
                FieldAttr::TransformSetParams(params) => {
                    result.transform_set_params = Some(params);
                }
            }
        }

        if result.convert.is_some()
            && (result.transform_get.is_some() || result.transform_set.is_some())
        {
            return Err(Error::new(
                field.span(),
                "Cannot use transform and convert on the same field.",
            ));
        }

        validate_transform(
            field,
            "transform_get",
            result.transform_get.as_deref(),
            result.transform_get_params.as_ref(),
        )?;
        validate_transform(
            field,
            "transform_set",
            result.transform_set.as_deref(),
            result.transform_set_params.as_ref(),
        )?;

        if result.is_key && !has_updatable_set {
            result.updatable = false;
        }
        if result.is_key && !has_patchable_set {
            result.patchable = false;
        }

        Ok(result)
    }
}

impl TryFrom<DeriveInput> for Entity {
    type Error = Error;

    fn try_from(input: DeriveInput) -> Result<Self> {
        let ident = input.ident.clone();
        let data_struct = match &input.data {
            Data::Struct(s) => s,
            _ => {
                return Err(Error::new(
                    input.span(),
                    "only structs can be used as entity",
                ))
            }
        };

        let mut table_name = None;
        let mut update = Ident::new("update", Span::call_site());
        let mut insert = None;
        let mut patch = None;
        let mut get_all = None;
        let mut delete = None;
        let mut before_patch = None;
        let mut after_patch = None;
        let mut before_update = None;
        let mut after_update = None;
        let mut before_insert = None;
        let mut after_insert = None;
        let mut before_delete = None;
        let mut after_delete = None;
        let mut error_type = None;
        let mut context_type = None;

        for attr in crate::attrs::parse_all::<EntityAttr>(&input.attrs)? {
            match attr {
                EntityAttr::Table(name) => table_name.replace(name).map_or(Ok(()), duplicate)?,
                EntityAttr::Update(fn_name) => {
                    if let Some(fn_name) = fn_name {
                        update = fn_name;
                    }
                }
                EntityAttr::Insertable(struct_ident) => {
                    let struct_ident = struct_ident.unwrap_or_else(|| {
                        Ident::new(&format!("Insert{}", ident), Span::call_site())
                    });
                    insert.replace(struct_ident).map_or(Ok(()), duplicate)?
                }
                EntityAttr::Patchable(struct_ident) => {
                    let struct_ident = struct_ident.unwrap_or_else(|| {
                        Ident::new(&format!("Patch{}", ident), Span::call_site())
                    });
                    patch.replace(struct_ident).map_or(Ok(()), duplicate)?
                }
                EntityAttr::GetAll(fn_name) => {
                    let fn_name =
                        fn_name.unwrap_or_else(|| Ident::new("get_all", Span::call_site()));
                    get_all.replace(fn_name).map_or(Ok(()), duplicate)?
                }
                EntityAttr::Deletable(fn_name) => {
                    let fn_name =
                        fn_name.unwrap_or_else(|| Ident::new("delete", Span::call_site()));
                    delete.replace(fn_name).map_or(Ok(()), duplicate)?
                }
                EntityAttr::BeforePatch(path) => before_patch = Some(path),
                EntityAttr::AfterPatch(path) => after_patch = Some(path),
                EntityAttr::BeforeUpdate(path) => before_update = Some(path),
                EntityAttr::AfterUpdate(path) => after_update = Some(path),
                EntityAttr::BeforeInsert(path) => before_insert = Some(path),
                EntityAttr::AfterInsert(path) => after_insert = Some(path),
                EntityAttr::BeforeDelete(path) => before_delete = Some(path),
                EntityAttr::AfterDelete(path) => after_delete = Some(path),
                EntityAttr::ErrorType(error_ident) => {
                    error_type = Some(error_ident);
                }
                EntityAttr::ContextType(context_ident) => {
                    context_type = Some(context_ident);
                }
            }
        }
        let table_name = table_name.ok_or_else(|| missing_attr("table"))?;

        let fields = get_fields(input.span(), data_struct)?
            .into_iter()
            .map(EntityField::try_from)
            .collect::<Result<Vec<_>>>()?;

        let table_keys: Vec<EntityField> = fields
            .iter()
            .filter(|field| field.is_key)
            .cloned()
            .collect();

        if table_keys.is_empty() {
            panic!("struct does not have a primary key or composite key")
        }

        Ok(Entity {
            table_name,
            fields,
            ident,
            vis: input.vis,
            update,
            insert,
            patch,
            get_all,
            delete,
            before_patch,
            after_patch,
            before_update,
            after_update,
            before_insert,
            after_insert,
            before_delete,
            after_delete,
            error_type,
            context_type,
        })
    }
}

fn get_fields(span: Span, input: &DataStruct) -> Result<Vec<&Field>> {
    match &input.fields {
        Fields::Named(FieldsNamed { named, .. }) => Ok(named.iter().collect()),
        _ => Err(Error::new(
            span,
            "only structs with named fields can be used as entity",
        )),
    }
}

fn duplicate<T>(_: T) -> Result<()> {
    Err(Error::new(Span::call_site(), "duplicate attribute"))
}

fn missing_attr(name: &str) -> Error {
    Error::new(
        Span::call_site(),
        format!(r#"missing #[ormx({} = "..")) attribute"#, name),
    )
}

fn is_option_type(ty: &Type) -> bool {
    let Type::Path(type_path) = ty else {
        return false;
    };

    let Some(segment) = type_path.path.segments.last() else {
        return false;
    };

    segment.ident == "Option"
}

fn validate_transform(
    field: &Field,
    attr_name: &str,
    template: Option<&str>,
    params_fn: Option<&ExprPath>,
) -> Result<()> {
    let Some(template) = template else {
        if params_fn.is_some() {
            return Err(Error::new(
                field.span(),
                format!("{attr_name}_params requires {attr_name}."),
            ));
        }
        return Ok(());
    };

    let required_params = count_transform_params(template);
    if required_params > 0 && params_fn.is_none() {
        return Err(Error::new(
            field.span(),
            format!("Field uses $param placeholders but {attr_name}_params is not provided."),
        ));
    }

    Ok(())
}
